/// Flutter icons HalenIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HalenIcon
///      fonts:
///       - asset: fonts/HalenIcon.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class HalenIcon {
  HalenIcon._();

  static const _kFontFam = 'HalenIcon';
  static const String? _kFontPkg = null;

  static const IconData mail =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogOutline =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessTime =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folderOpen =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashOutline =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refer =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  // static const IconData retail =
  //     IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  // static const IconData rideshareCard =
  //     IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData home =
  //     IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groceries =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// static const IconData user =
//     IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// static const IconData chalkboard =
//     IconData(0xf51b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// static const IconData moneyBill =
//     IconData(0xf53a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
